# Generated by Django 3.2.16 on 2023-07-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230706_1201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
